plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.moddev' version "${mdg_version}"
}

def isSnapshot = System.getenv('SNAPSHOT') == 'true'
version = "${minecraft_version}-${mod_version}${isSnapshot ? '-SNAPSHOT' : ''}"
group = mod_group_id

base {
    archivesName = mod_id
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(25)
    withSourcesJar()
}

sourceSets {
    test {
        compileClasspath += main.output + main.compileClasspath
        runtimeClasspath += main.output + main.runtimeClasspath
    }
}

sourceSets.main.resources.srcDir 'src/generated/resources'

repositories {
    mavenCentral()
    maven {
        name = 'NeoForged'
        url = 'https://maven.neoforged.net/releases'
    }
    maven {
        name = 'BlameJared'
        url = 'https://maven.blamejared.com/'
        content { includeGroup 'mezz.jei' }
    }
    maven {
        name = 'Modrinth'
        url = 'https://api.modrinth.com/maven'
        content { includeGroup 'maven.modrinth' }
    }
}

neoForge {
    version = neoforge_version

    interfaceInjectionData.from provider {
        zipTree(configurations.geckolibInterfaces.singleFile)
                .matching { include 'META-INF/interface_injections.json' }
    }

    runs {
        configureEach {
            logLevel = org.slf4j.event.Level.INFO
        }

        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
        }

        gameTestServer {
            type = 'gameTestServer'
            systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
            gameDirectory = project.file('run-gametest')
        }

        clientData {
            clientData()
            programArguments.addAll '--mod', mod_id,
                    '--all',
                    '--output', file('src/generated/resources/').getAbsolutePath(),
                    '--existing', file('src/main/resources/').getAbsolutePath()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
            sourceSet sourceSets.test
        }
    }
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
    geckolibInterfaces
}

dependencies {
    geckolibInterfaces "maven.modrinth:geckolib:${geckolib_version}"

    compileOnly "io.github.llamalad7:mixinextras-common:${mixinextras_version}"
    annotationProcessor "io.github.llamalad7:mixinextras-common:${mixinextras_version}"

    implementation "maven.modrinth:geckolib:${geckolib_version}"

    compileOnly "mezz.jei:jei-${minecraft_version}-common-api:${jei_version}"
    compileOnly "mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_version}"
    localRuntime "mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}"

    compileOnly "maven.modrinth:jade:${jade_version}"
    localRuntime "maven.modrinth:jade:${jade_version}"
}

tasks.named('test', Test).configure {
    failOnNoDiscoveredTests = false
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 25
}

tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neoforge_version       : neoforge_version,
            neoforge_version_range : neoforge_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_credits            : mod_credits,
            mod_description        : mod_description
    ]

    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes([
                'Specification-Title'     : mod_id,
                'Specification-Vendor'    : mod_authors,
                'Specification-Version'   : '1',
                'Implementation-Title'    : project.name,
                'Implementation-Version'  : project.version,
                'Implementation-Vendor'   : mod_authors,
                'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            name = 'BreakInBlocks'
            url = isSnapshot
                    ? 'https://maven.breakinblocks.com/snapshots'
                    : 'https://maven.breakinblocks.com/releases'
            credentials {
                username = System.getenv('MAVEN_USER') ?: ''
                password = System.getenv('MAVEN_TOKEN') ?: ''
            }
        }
    }
}
