## Environment
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

## Mod properties
mod_id=kindredspirits
mod_name=Kindred Spirits
mod_license=All Rights Reserved
mod_version=1.0.7
mod_group_id=com.breakinblocks.kindredspirits
mod_authors=Saereth, AlfredGG
mod_credits=Nightfox model, texture and animations by samus2002 (RPG Pet Pack Vol.2 - Oriental), used under licence.
mod_description=Bond with a spirit companion that grows alongside you, gaining levels and new abilities.

## Environment versions
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neoforge_version=21.1.249
neoforge_version_range=[21.1.200,)
loader_version_range=[4,)

## Toolchain
mdg_version=2.0.141

## Dependencies
mixinextras_version=0.4.1
geckolib_version=4.9.3
jei_version=19.27.0.340
jade_version=15.10.6+neoforge
oracle_index_version=7OqGasX2
curios_version=9.5.1+1.21.1
architectury_version=ZxYGwlk0
